## Exercício 1: NumPy array Indexing/Slicing

1.1) Neste exercício, vamos usar o iris dataset. Carrega o iris.csv
usando o método read apropriado para o tipo de ficheiro.


In [4]:
import sys
PATHS = ["si/src/si/data", "src/si/io_folder"]
sys.path.append(PATHS)

from si.io_folder.csv_file import read_csv

In [6]:
iris = read_csv('C:/Users/beatr/Mestrado/2ºano/si/datasets/iris.csv', sep=',', features=True, label=True)

 1.2 Seleciona a primeira variável independente e verifica a
dimensão do array resultante

In [10]:
var_ind = iris.X[:,0].shape
var_ind

(150,)

1.3) Seleciona as últimas 5 amostras do iris dataset. Qual a
média das últimas 5 amostras para cada variável
independente/feature?

In [13]:
last_five = iris.X[-5:]

dependent_variables_names = iris.features[:-1]
print(dependent_variables_names)

means = iris.X[-5:,].mean(axis=0)
#axis = 0 -> média por coluna, axis = 1 -> média por linha
print(means)
#media para cada feature, considerando cinco ultimas amostras

['sepal_length', 'sepal_width', 'petal_length']
[6.32 2.98 5.18 2.06]


1.4) Seleciona todas as amostras do dataset com valor superior
ou igual a 1. Nota que o array resultante deve ter apenas
amostras com valores iguais ou superiores a 1 para todas as
features.

In [16]:
import numpy as np

arr = iris.X
mask14 = np.all(arr[:,] >= 1, axis = 1)
sol_arr = arr[mask14]
print(len(sol_arr))
print(sol_arr)

100
[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.

1.5) Seleciona todas as amostras com a classe/label igual a ‘Irissetosa’. Quantas amostras obténs?

In [19]:
arr = iris.X
mask_setosa = (iris.y =="Iris-setosa")
new_arr = arr[mask_setosa]
print("New array - Iris-setosa")
print(new_arr)
print(len(new_arr))

New array - Iris-setosa
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]]
50


## Exercício 2: NumPy array Indexing/Slicing

2.1) Adiciona um método ao objeto Dataset que remove todas as
amostras que contêm pelo menos um valor nulo (NaN). Nota que o
objeto resultante não deve conter valores nulos em para nenhuma
feature/variável independente. Nota também que deves atualizar o
vetor y removendo as entradas associadas às amostras a remover.
Deves usar apenas funções no NumPy. Nome do método: dropna

In [ ]:
import numpy as np

def dropna (self):

    """
    Remove missing values.
    Parameters : axis {0 index, 1 for columns}, default 0
                 how { 'any', 'all'} ‘any’ drops the row/column if ANY value is Null and  ‘all’ drops only if ALL values are null. Default 'any'
    """
    #remove NaN from samples
    self.x = self.x[~np.isnan(self.x).any(axis=1)]

    #update y
    if self.has_labels():
        self.y = self.y[~np.isnan(self.x).any(axis=1)]


2.2) Adiciona um método ao objeto Dataset que substitui todas os
valores nulos por outro valor (argumento da função/método). Nota
que o objeto resultante não deve conter valores nulos em para
nenhuma feature/variável independente. Deves usar apenas funções
no NumPy. Nome do método: fillna

In [ ]:
import numpy as np

def fillna(self, value):

        """
        Fill NA/NaN values using the specified method.
        Parameters: value - scalar, dict, Series, or DataFrame
                    method{‘backfill’, ‘bfill’, ‘pad’, ‘ffill’, None}, default None
        """

        # substitui todas os valores nulos por outro valor (argumento da função/método)

        self.x = np.nan_to_num(self.x, nan=value)

        # atualizar y
        if self.has_labels():
            self.y = np.nan_to_num(self.y, nan=value)